/*
 * Service Catalog Management
 *
 * ## TMF API Reference: TMF633 - Service Catalog Management   Version 4.0   The Service Catalog API is one of Catalog Management API Family. Service Catalog API goal is to provide a catalog of services.  Service Catalog API performs the following operations on the resource : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events. .  Copyright © TM Forum 2020. All Rights Reserved. 
 *
 * API version: 4.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tmf633

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// ImportJobApiController binds http requests to an api service and writes the service results to the http response
type ImportJobApiController struct {
	service ImportJobApiServicer
	errorHandler ErrorHandler
}

// ImportJobApiOption for how the controller is set up.
type ImportJobApiOption func(*ImportJobApiController)

// WithImportJobApiErrorHandler inject ErrorHandler into controller
func WithImportJobApiErrorHandler(h ErrorHandler) ImportJobApiOption {
	return func(c *ImportJobApiController) {
		c.errorHandler = h
	}
}

// NewImportJobApiController creates a default api controller
func NewImportJobApiController(s ImportJobApiServicer, opts ...ImportJobApiOption) Router {
	controller := &ImportJobApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ImportJobApiController
func (c *ImportJobApiController) Routes() Routes {
	return Routes{ 
		{
			"CreateImportJob",
			strings.ToUpper("Post"),
			"/tmf-api/serviceCatalogManagement/v4/importJob",
			c.CreateImportJob,
		},
		{
			"DeleteImportJob",
			strings.ToUpper("Delete"),
			"/tmf-api/serviceCatalogManagement/v4/importJob/{id}",
			c.DeleteImportJob,
		},
		{
			"ListImportJob",
			strings.ToUpper("Get"),
			"/tmf-api/serviceCatalogManagement/v4/importJob",
			c.ListImportJob,
		},
		{
			"RetrieveImportJob",
			strings.ToUpper("Get"),
			"/tmf-api/serviceCatalogManagement/v4/importJob/{id}",
			c.RetrieveImportJob,
		},
	}
}

// CreateImportJob - Creates a ImportJob
func (c *ImportJobApiController) CreateImportJob(w http.ResponseWriter, r *http.Request) {
	importJobParam := ImportJobCreate{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&importJobParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertImportJobCreateRequired(importJobParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateImportJob(r.Context(), importJobParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// DeleteImportJob - Deletes a ImportJob
func (c *ImportJobApiController) DeleteImportJob(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	
	result, err := c.service.DeleteImportJob(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ListImportJob - List or find ImportJob objects
func (c *ImportJobApiController) ListImportJob(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	fieldsParam := query.Get("fields")
	offsetParam, err := parseInt32Parameter(query.Get("offset"), false)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	limitParam, err := parseInt32Parameter(query.Get("limit"), false)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.ListImportJob(r.Context(), fieldsParam, offsetParam, limitParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// RetrieveImportJob - Retrieves a ImportJob by ID
func (c *ImportJobApiController) RetrieveImportJob(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	idParam := params["id"]
	
	fieldsParam := query.Get("fields")
	result, err := c.service.RetrieveImportJob(r.Context(), idParam, fieldsParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
