/*
 * Service Catalog Management
 *
 * ## TMF API Reference: TMF633 - Service Catalog Management   Version 4.0   The Service Catalog API is one of Catalog Management API Family. Service Catalog API goal is to provide a catalog of services.  Service Catalog API performs the following operations on the resource : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events. .  Copyright © TM Forum 2020. All Rights Reserved. 
 *
 * API version: 4.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tmf633

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// EventsSubscriptionApiController binds http requests to an api service and writes the service results to the http response
type EventsSubscriptionApiController struct {
	service EventsSubscriptionApiServicer
	errorHandler ErrorHandler
}

// EventsSubscriptionApiOption for how the controller is set up.
type EventsSubscriptionApiOption func(*EventsSubscriptionApiController)

// WithEventsSubscriptionApiErrorHandler inject ErrorHandler into controller
func WithEventsSubscriptionApiErrorHandler(h ErrorHandler) EventsSubscriptionApiOption {
	return func(c *EventsSubscriptionApiController) {
		c.errorHandler = h
	}
}

// NewEventsSubscriptionApiController creates a default api controller
func NewEventsSubscriptionApiController(s EventsSubscriptionApiServicer, opts ...EventsSubscriptionApiOption) Router {
	controller := &EventsSubscriptionApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the EventsSubscriptionApiController
func (c *EventsSubscriptionApiController) Routes() Routes {
	return Routes{ 
		{
			"RegisterListener",
			strings.ToUpper("Post"),
			"/tmf-api/serviceCatalogManagement/v4/hub",
			c.RegisterListener,
		},
		{
			"UnregisterListener",
			strings.ToUpper("Delete"),
			"/tmf-api/serviceCatalogManagement/v4/hub/{id}",
			c.UnregisterListener,
		},
	}
}

// RegisterListener - Register a listener
func (c *EventsSubscriptionApiController) RegisterListener(w http.ResponseWriter, r *http.Request) {
	dataParam := EventSubscriptionInput{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&dataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertEventSubscriptionInputRequired(dataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RegisterListener(r.Context(), dataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// UnregisterListener - Unregister a listener
func (c *EventsSubscriptionApiController) UnregisterListener(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	
	result, err := c.service.UnregisterListener(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
