/*
 * Service Catalog Management
 *
 * ## TMF API Reference: TMF633 - Service Catalog Management   Version 4.0   The Service Catalog API is one of Catalog Management API Family. Service Catalog API goal is to provide a catalog of services.  Service Catalog API performs the following operations on the resource : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events. .  Copyright © TM Forum 2020. All Rights Reserved. 
 *
 * API version: 4.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tmf633

import (
	"time"
)

// ImportJob - Represents a task used to import resources from a file
type ImportJob struct {

	// Identifier of the import job
	Id string `json:"id,omitempty"`

	// Reference of the import job
	Href string `json:"href,omitempty"`

	// Date at which the job was completed
	CompletionDate time.Time `json:"completionDate,omitempty"`

	// Indicates the format of the imported data
	ContentType string `json:"contentType,omitempty"`

	// Date at which the job was created
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Reason for failure if status is failed
	ErrorLog string `json:"errorLog,omitempty"`

	// URL of the root resource where the content of the file specified by the import job must be applied
	Path string `json:"path,omitempty"`

	// URL of the file containing the data to be imported
	Url string `json:"url,omitempty"`

	Status JobStateType `json:"status,omitempty"`
}

// AssertImportJobRequired checks if the required fields are not zero-ed
func AssertImportJobRequired(obj ImportJob) error {
	return nil
}

// AssertRecurseImportJobRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ImportJob (e.g. [][]ImportJob), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseImportJobRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aImportJob, ok := obj.(ImportJob)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertImportJobRequired(aImportJob)
	})
}
