/*
 * Service Catalog Management
 *
 * ## TMF API Reference: TMF633 - Service Catalog Management   Version 4.0   The Service Catalog API is one of Catalog Management API Family. Service Catalog API goal is to provide a catalog of services.  Service Catalog API performs the following operations on the resource : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events. .  Copyright © TM Forum 2020. All Rights Reserved. 
 *
 * API version: 4.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tmf633

// ServiceSpecRelationship - A dependency, substitution or exclusivity relationship between/among service specifications.
type ServiceSpecRelationship struct {

	// unique identifier
	Id string `json:"id,omitempty"`

	// Hyperlink reference
	Href string `json:"href,omitempty"`

	// Name of the related entity.
	Name string `json:"name,omitempty"`

	// Type of relationship such as dependency, substitution or exclusivity
	RelationshipType string `json:"relationshipType"`

	// The association role for this service specification
	Role string `json:"role,omitempty"`

	ValidFor TimePeriod `json:"validFor,omitempty"`

	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`

	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`

	// When sub-classing, this defines the sub-class Extensible name
	Type string `json:"@type,omitempty"`

	// The actual type of the target instance when needed for disambiguation.
	ReferredType string `json:"@referredType,omitempty"`
}

// AssertServiceSpecRelationshipRequired checks if the required fields are not zero-ed
func AssertServiceSpecRelationshipRequired(obj ServiceSpecRelationship) error {
	elements := map[string]interface{}{
		"relationshipType": obj.RelationshipType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTimePeriodRequired(obj.ValidFor); err != nil {
		return err
	}
	return nil
}

// AssertRecurseServiceSpecRelationshipRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ServiceSpecRelationship (e.g. [][]ServiceSpecRelationship), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseServiceSpecRelationshipRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aServiceSpecRelationship, ok := obj.(ServiceSpecRelationship)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertServiceSpecRelationshipRequired(aServiceSpecRelationship)
	})
}
